name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  PrintProcessingSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS version
        run: uname -a

      - name: Print Node.js version
        run: node --version

      - name: Print npm version
        run: npm --version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintProcessingSoftwareVersions]
    steps:
      - name: Install MongoDB
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb

      - name: Print MongoDB version
        run: mongod --version
