name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  PrintProcessingSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS version
        run: uname -a

      - name: Print Node.js version
        run: node --version

      - name: Print npm version
        run: npm --version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintProcessingSoftwareVersions]
    steps:
      - name: Install MongoDB
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb.gpg
          echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org

      - name: Print MongoDB version
        run: mongod --version
