name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  PrintProcessingSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS version
        run: uname -a

      - name: Print Node.js version
        run: node --version

      - name: Print npm version
        run: npm --version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintProcessingSoftwareVersions]
    steps:
      - name: Run MongoDB container
        run: |
          docker run --rm mongo:7.0 mongod --version
