name: Javascript Code Linter
on:
  push:
    branches:
      - main

jobs:
  JavaScriptCodeLinter:
    runs-on: ubuntu-latest
    steps:
      # Клонування репозиторію
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      # Встановлення Biome
      - name: Install JSON/JS Linter
        run: npm install --save-dev --save-exact @biomejs/biome

      # Перевірка JS файлів, ігноруючи package.json
      - name: Validate all JS files
        run: npx @biomejs/biome check
        env:
          FILTER_REGEX_EXCLUDE: package.json
